/* Auto-generated by scripts/generate-blog-posts.mjs - do not edit by hand. */
import type { BlogPostDefinition } from './types';

export const blogPosts: BlogPostDefinition[] = [
	{
		id: "worth",
		imageKey: "cheatsPackage",
		published: "2026-08-20",
		updated: "2026-09-14",
		category: "Opinion",
		featured: true,
		translations: {
		en: {
		slug: "is-it-worth-it",
		title: "Is it worth it? Honest take after 3 wipes",
		metaDescription: "Is it worth it? Long-time buyers weigh in after several wipes on Windows PC - ESP, aimbot, and what actually changed their raids.",
		h1: "Is it worth it?",
		intro: "For anyone running this long term - is it actually worth it, or does it get old fast?",
		keywords: ["tarkov cheats worth it","tarkov cheats review"],
		imageAlt: "Tarkov raid loadout after buying cheats on Windows PC",
		sections: [
			{
				h2: "",
				paragraphs: [
					"Been on the fence for a while. For anyone who has run this over a few wipes - is it worth it, or does it get old fast? I mostly do Customs and Interchange, not really an Arena player.",
					"What I care about is staying alive and saving time on loot, not rage clips. Before I grab a plan on the <a href=\"/pricing/\">Pricing</a> page I just want an honest take from people who actually use it.",
				],
			}
		],
	},
		},
	},
	{
		id: "compare",
		imageKey: "cheatsPackage",
		published: "2026-08-21",
		updated: "2026-09-13",
		category: "Comparison",
		featured: true,
		translations: {
		en: {
		slug: "how-does-it-compare",
		title: "How does it compare to other providers?",
		metaDescription: "How does it compare to other Tarkov cheat providers? Buyers explain what made them switch - one package, patch rebuilds, no Lite/Full bait.",
		h1: "How does it compare?",
		intro: "Coming from a provider that kept going dark after patches - how does this one compare?",
		keywords: ["tarkov cheat comparison","best tarkov cheats"],
		imageAlt: "Comparing Tarkov cheat providers before buying",
		sections: [
			{
				h2: "",
				paragraphs: [
					"My last provider kept going dark after every BattlEye wave. How does this one compare - is it actually maintained, and is everything included or is there a Lite/Full split?",
					"I do not want to pay and then find out ESP or loot filters are behind a higher tier. What am I actually getting here vs the other shops? The <a href=\"/features/\">Features</a> list looks like one package but I want to hear it from buyers.",
				],
			}
		],
	},
		},
	},
	{
		id: "esp",
		imageKey: "espWallhack",
		published: "2026-08-22",
		updated: "2026-09-15",
		category: "ESP",
		featured: false,
		translations: {
		en: {
		slug: "esp-not-showing-in-raid",
		title: "ESP not showing in raid",
		metaDescription: "ESP not showing in raid on a green status? Players walk through the fixes - Cloud DMA, launch order, and overlay conflicts on Windows PC.",
		h1: "ESP not showing in raid",
		intro: "Overlay draws but player ESP is not showing at all, even on a green status.",
		keywords: ["tarkov esp not working","esp not showing"],
		imageAlt: "Player ESP boxes drawn in a Tarkov raid",
		sections: [
			{
				h2: "",
				paragraphs: [
					"Loaded into a raid and the overlay draws fine, but player ESP is not showing at all. The <a href=\"/updates/\">Updates</a> page is green so I do not think it is a patch. Fresh Windows 11 install.",
					"Menu opens, the toggles are on, but in raid I get nothing on screen. What should I check before I open a support ticket?",
				],
			}
		],
	},
		},
	},
	{
		id: "buy",
		imageKey: "cheatsPackage",
		published: "2026-08-23",
		updated: "2026-09-12",
		category: "Store",
		featured: false,
		translations: {
		en: {
		slug: "how-do-i-get-access",
		title: "How do I buy and get access?",
		metaDescription: "How to buy and get access on Windows PC - checkout, instant delivery, and where your key and download show up after payment.",
		h1: "How do I get access?",
		intro: "First time buyer - how does checkout work and where do I get access after paying?",
		keywords: ["buy tarkov cheats","how to get access"],
		imageAlt: "Checkout flow to buy Tarkov cheats and get access",
		sections: [
			{
				h2: "",
				paragraphs: [
					"First time buyer here. How do I buy and get access - do I get a key instantly after checkout, and where do I download from?",
					"I also want to make sure I grab the raids license and not the wrong product. Can someone link the right page so I do not get access to something I did not mean to buy?",
				],
			}
		],
	},
		},
	},
	{
		id: "price",
		imageKey: "cheatsPackage",
		published: "2026-08-24",
		updated: "2026-09-11",
		category: "Store",
		featured: false,
		translations: {
		en: {
		slug: "how-much-does-it-cost",
		title: "How much does it cost?",
		metaDescription: "How much does it cost? Current monthly and lifetime pricing on Windows PC, and which plan makes sense if you play on and off.",
		h1: "How much does it cost?",
		intro: "How much does it cost right now, and is the feature set the same on monthly and lifetime?",
		keywords: ["tarkov cheat price","tarkov cheats cost"],
		imageAlt: "Tarkov cheat pricing plans on Windows PC",
		sections: [
			{
				h2: "",
				paragraphs: [
					"Trying to work out the pricing. How much does it cost for monthly vs lifetime right now, and is the feature set the same on both plans?",
					"I play on and off depending on the wipe, so I am not sure lifetime is worth it yet. What do people actually run? Live numbers are on <a href=\"/pricing/\">Pricing</a> but I want the real-world view.",
				],
			}
		],
	},
		},
	},
	{
		id: "reqs",
		imageKey: "playerEsp",
		published: "2026-08-25",
		updated: "2026-09-10",
		category: "Product",
		featured: false,
		translations: {
		en: {
		slug: "system-requirements",
		title: "What are the system requirements?",
		metaDescription: "System requirements before you buy - Windows 10/11, Cloud DMA, and the BIOS settings you need on for the full menu to load.",
		h1: "System requirements?",
		intro: "What are the system requirements - is a single Windows 11 gaming PC enough?",
		keywords: ["tarkov cheat requirements","windows 11"],
		imageAlt: "Windows PC meeting Tarkov cheat system requirements",
		sections: [
			{
				h2: "",
				paragraphs: [
					"Before I buy, what are the actual system requirements? I am on Windows 11, a normal gaming rig, single PC. Is that enough or do I need a second machine?",
					"I keep seeing Cloud DMA mentioned and I am not sure if that means extra hardware. Want to confirm the requirements before I pay.",
				],
			}
		],
	},
		},
	},
	{
		id: "loot",
		imageKey: "espWallhack",
		published: "2026-08-26",
		updated: "2026-09-15",
		category: "ESP",
		featured: false,
		translations: {
		en: {
		slug: "loot-esp-too-cluttered",
		title: "Loot ESP too cluttered - how to filter?",
		metaDescription: "Loot ESP too cluttered? Set a price floor and filter presets so Interchange and Labs stay readable on Windows PC raids.",
		h1: "Loot ESP too cluttered",
		intro: "Loot ESP is way too cluttered - every bolt and bandage shows. How do I filter it down to the valuable stuff?",
		keywords: ["tarkov loot esp","loot filter"],
		imageAlt: "Filtered loot ESP on Interchange in Tarkov",
		sections: [
			{
				h2: "",
				paragraphs: [
					"My loot ESP is on but it is too cluttered - every bolt, bandage and screw shows up. Interchange is a wall of text and I cannot find the good stuff.",
					"How do you filter this down so only the valuable loot shows? There must be a price floor setting somewhere.",
				],
			}
		],
	},
		},
	},
	{
		id: "aimbot",
		imageKey: "aimbotCombat",
		published: "2026-08-27",
		updated: "2026-09-14",
		category: "Aimbot",
		featured: false,
		translations: {
		en: {
		slug: "best-aimbot-settings",
		title: "Best aimbot settings to look legit?",
		metaDescription: "Best aimbot settings so killcams look human - FOV, visible check, smart bone, and prediction values buyers actually run.",
		h1: "Best aimbot settings",
		intro: "Aimbot feels robotic and the killcams look obvious - what are the best settings?",
		keywords: ["tarkov aimbot settings","legit aimbot"],
		imageAlt: "Aimbot FOV and bone settings in Tarkov",
		sections: [
			{
				h2: "",
				paragraphs: [
					"My aimbot feels robotic and the killcams look obvious. What are the best settings to keep it subtle - FOV, bone selection, visible check?",
					"I would rather win close fights and not get clipped than snap across the map. What values do you all run?",
				],
			}
		],
	},
		},
	},
	{
		id: "wallhack",
		imageKey: "espWallhack",
		published: "2026-08-28",
		updated: "2026-09-09",
		category: "ESP",
		featured: false,
		translations: {
		en: {
		slug: "wallhack-and-chams",
		title: "Wallhack / chams - what do you run?",
		metaDescription: "Wallhack and chams settings for raids - box vs skeleton vs chams, visible check, and keeping the screen readable in a fight.",
		h1: "Wallhack and chams",
		intro: "For seeing players through walls - boxes, skeleton or chams? Chams feel distracting.",
		keywords: ["tarkov wallhack","tarkov chams"],
		imageAlt: "Wallhack chams on players through a wall in Tarkov",
		sections: [
			{
				h2: "",
				paragraphs: [
					"New to this. For a wallhack, do you run boxes, skeleton or chams? The chams look cool but feel distracting in an actual fight.",
					"Trying to find the cleanest wallhack and chams setup that still reads well on Factory close range.",
				],
			}
		],
	},
		},
	},
	{
		id: "patch",
		imageKey: "headerArt",
		published: "2026-08-29",
		updated: "2026-09-15",
		category: "Status",
		featured: false,
		translations: {
		en: {
		slug: "safe-to-play-after-a-patch",
		title: "Safe to play after a patch?",
		metaDescription: "Safe to play after a game or BattlEye patch? How rebuilds work, where to check status, and why you wait for green first.",
		h1: "Safe to play after a patch?",
		intro: "Game patched this morning - is it safe to play after a patch or do I wait for a rebuild?",
		keywords: ["tarkov cheat after patch","undetected update"],
		imageAlt: "Checking status after a Tarkov patch before loading in",
		sections: [
			{
				h2: "",
				paragraphs: [
					"Game patched this morning. Is it safe to play after a patch, or do I wait for a rebuild? I do not want to be the guy who queues on day one and gets flagged.",
					"Where is the right place to check status before I load in?",
				],
			}
		],
	},
		},
	},
	{
		id: "arena",
		imageKey: "playerEsp",
		published: "2026-08-30",
		updated: "2026-09-08",
		category: "Product",
		featured: false,
		translations: {
		en: {
		slug: "does-it-work-in-arena",
		title: "Does it work in Arena?",
		metaDescription: "Does the raids license work in Tarkov Arena? Short answer from staff plus why Arena needs a separate product on Windows PC.",
		h1: "Does it work in Arena?",
		intro: "Does it work in Arena, or is the raids license separate from Tarkov Arena?",
		keywords: ["tarkov arena cheat","arena"],
		imageAlt: "Tarkov Arena match on Windows PC",
		sections: [
			{
				h2: "",
				paragraphs: [
					"About to buy but I want to confirm - does it work in Arena, or is Tarkov Arena a separate product?",
					"I do not want to pay and then find out my Arena matches are not covered by this key.",
				],
			}
		],
	},
		},
	},
	{
		id: "dma",
		imageKey: "cheatsPackage",
		published: "2026-08-31",
		updated: "2026-09-13",
		category: "Setup",
		featured: false,
		translations: {
		en: {
		slug: "cloud-dma-setup",
		title: "Cloud DMA setup help",
		metaDescription: "Cloud DMA setup walkthrough - what it is, why it is required, and the HVCI and Secure Boot steps for a full menu on launch.",
		h1: "Cloud DMA setup",
		intro: "What is Cloud DMA and how do I set it up? Do I need a second PC and a card?",
		keywords: ["cloud dma","tarkov dma setup"],
		imageAlt: "Cloud DMA setup steps for Tarkov on Windows PC",
		sections: [
			{
				h2: "",
				paragraphs: [
					"I keep seeing Cloud DMA is required but I do not fully get what it is or how the setup works. Do I need a second PC and a DMA card, or is this different?",
					"On my first launch the menu was half greyed out and I panicked. I want to do the Cloud DMA setup properly this time - the <a href=\"/setup/\">Setup</a> page has steps but I want a plain-English version.",
				],
			}
		],
	},
		},
	},
	{
		id: "recoil",
		imageKey: "aimbotCombat",
		published: "2026-09-01",
		updated: "2026-09-12",
		category: "Aimbot",
		featured: false,
		translations: {
		en: {
		slug: "no-recoil-settings",
		title: "No recoil settings?",
		metaDescription: "No recoil and no sway settings - how much to run, when to dial it back, and saving a profile so you do not retune each session.",
		h1: "No recoil settings",
		intro: "Do you run no recoil and no sway maxed all the time, or is that a giveaway?",
		keywords: ["tarkov no recoil","no sway"],
		imageAlt: "No recoil spray pattern in Tarkov",
		sections: [
			{
				h2: "",
				paragraphs: [
					"Do you run no recoil and no sway maxed all the time, or is that a giveaway? Mine feels floaty on full auto.",
					"Looking for sane no recoil settings that do not look ridiculous in a clip.",
				],
			}
		],
	},
		},
	},
	{
		id: "radar",
		imageKey: "espWallhack",
		published: "2026-09-02",
		updated: "2026-09-10",
		category: "ESP",
		featured: false,
		translations: {
		en: {
		slug: "is-radar-worth-it",
		title: "Is the radar worth using?",
		metaDescription: "Is the radar worth using over on-screen ESP? Players compare the map radar, distance, and arrows for spotting third parties.",
		h1: "Is radar worth it?",
		intro: "Is the radar worth it over normal on-screen ESP, or is on-screen ESP enough?",
		keywords: ["tarkov radar","radar hack"],
		imageAlt: "Radar map showing players in a Tarkov raid",
		sections: [
			{
				h2: "",
				paragraphs: [
					"Is the radar worth using, or is normal ESP enough? I keep tunnel-visioning on the boxes and getting third-partied.",
					"Wondering if a minimap-style radar helps me read the whole map better instead of just what is in front of me.",
				],
			}
		],
	},
		},
	},
	{
		id: "grey",
		imageKey: "cheatsPackage",
		published: "2026-09-03",
		updated: "2026-09-15",
		category: "Setup",
		featured: false,
		translations: {
		en: {
		slug: "menu-greyed-out",
		title: "Menu greyed out on launch",
		metaDescription: "Menu greyed out with no ESP? The usual cause is HVCI or Secure Boot off in BIOS - here is the fix that works for most people.",
		h1: "Menu greyed out",
		intro: "Loader runs and the menu opens, but every toggle is greyed out - no ESP or aimbot.",
		keywords: ["menu greyed out","cheat not loading"],
		imageAlt: "Greyed out cheat menu on first launch",
		sections: [
			{
				h2: "",
				paragraphs: [
					"Loader runs, the menu opens, but it is all greyed out and I get no ESP or aimbot. The overlay itself shows. Status is green.",
					"Windows says Core Isolation is on. What actually causes the menu to be greyed out and how do I fix it?",
				],
			}
		],
	},
		},
	},
	{
		id: "delivery",
		imageKey: "cheatsPackage",
		published: "2026-09-04",
		updated: "2026-09-14",
		category: "Store",
		featured: false,
		translations: {
		en: {
		slug: "order-not-delivered",
		title: "Order not delivered after payment",
		metaDescription: "Paid but the order is not delivered yet? What to check first, how long delivery takes, and what Support needs to sort it fast.",
		h1: "Order not delivered",
		intro: "Paid and the order is not delivered yet - card was charged. Is delivery instant?",
		keywords: ["order not delivered","key not received"],
		imageAlt: "Checking order delivery after paying for Tarkov cheats",
		sections: [
			{
				h2: "",
				paragraphs: [
					"Paid a few minutes ago and my order is not delivered - I do not see a key or download anywhere, but the card was charged. Is delivery instant or is there a delay?",
					"Getting a little nervous. What do I do if the order still does not show up?",
				],
			}
		],
	},
		},
	},
	{
		id: "safe",
		imageKey: "headerArt",
		published: "2026-09-05",
		updated: "2026-09-15",
		category: "Status",
		featured: false,
		translations: {
		en: {
		slug: "is-it-undetected",
		title: "Is it actually undetected?",
		metaDescription: "Is it actually undetected and safe on Windows PC? What undetected really means and how BattlEye waves are handled between rebuilds.",
		h1: "Is it undetected?",
		intro: "Before I risk my account - is it undetected right now, and how safe is it long term?",
		keywords: ["tarkov cheat undetected","is it safe"],
		imageAlt: "Undetected status for Tarkov cheats on Windows PC",
		sections: [
			{
				h2: "",
				paragraphs: [
					"Real question before I risk my account - is it undetected right now, and how safe is it long term with BattlEye?",
					"I know nothing is ever 100%. I just want to understand how you keep it safe and what I should avoid doing on my end.",
				],
			}
		],
	},
		},
	},
	{
		id: "obs",
		imageKey: "espWallhack",
		published: "2026-09-06",
		updated: "2026-09-11",
		category: "ESP",
		featured: false,
		translations: {
		en: {
		slug: "streamproof-on-obs",
		title: "Is it streamproof on OBS?",
		metaDescription: "Is the overlay streamproof on OBS and Discord? Buyers share capture tests so your ESP and menu stay off the recording.",
		h1: "Streamproof on OBS?",
		intro: "Is the overlay streamproof on OBS, or will my ESP and menu show up in the recording?",
		keywords: ["streamproof","obs capture"],
		imageAlt: "Streamproof overlay hidden from OBS capture",
		sections: [
			{
				h2: "",
				paragraphs: [
					"I clip for a small Discord. Is the overlay streamproof on OBS, or will my ESP and menu show up in the recording?",
					"I do not want to expose myself in a highlight. Has anyone tested OBS game capture with it on?",
				],
			}
		],
	},
		},
	}
];
